#!/usr/bin/env python3
"""Generate release/test matrix docs from pyproject classifiers + tested_environments snapshot."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
from typing import Any

README_START = "<!-- AUTO-TEST-MATRIX:BEGIN -->"
README_END = "<!-- AUTO-TEST-MATRIX:END -->"
DOCS_START = README_START
DOCS_END = README_END


def _replace_between(text: str, start: str, end: str, payload: str) -> str:
    if start not in text or end not in text:
        raise ValueError(f"markers not found: {start} .. {end}")
    left, rest = text.split(start, 1)
    _, right = rest.split(end, 1)
    return left + start + "\n\n" + payload.rstrip() + "\n\n" + end + right


def _md_table(headers: list[str], rows: list[list[str]]) -> str:
    head = "| " + " | ".join(headers) + " |"
    sep = "| " + " | ".join(["---"] * len(headers)) + " |"
    body = ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join([head, sep, *body])


def _write_or_check(path: Path, content: str, *, check: bool) -> bool:
    old = path.read_text(encoding="utf-8")
    changed = old != content
    if changed and not check:
        path.write_text(content, encoding="utf-8")
    return changed


def _load_pyproject_python_versions(pyproject: Path) -> list[str]:
    text = pyproject.read_text(encoding="utf-8")
    found = set(re.findall(r'Programming Language :: Python :: (3\.[0-9]+)', text))
    return sorted(found, key=lambda v: tuple(int(p) for p in v.split(".")))


def _render_payload(*, py_versions: list[str], env_rows: list[dict[str, Any]], contract: dict[str, Any]) -> str:
    lines: list[str] = []
    lines.append("### Release/Test Matrix (Auto-generated)")
    lines.append("")
    lines.append(f"- Contract version: `{contract.get('contract_version', '-')}`")
    lines.append(f"- As-of date: `{contract.get('as_of_date', '-')}`")
    lines.append("- Source of truth: `docs/tested_environments.json` + `pyproject.toml` classifiers")
    lines.append("- Generated by: `python scripts/generate_test_matrix_docs.py`")
    lines.append("")

    py_rows = [[v] for v in py_versions] if py_versions else [["-"]]
    lines.append("#### Supported Python Classifiers")
    lines.append("")
    lines.append(_md_table(["Python"], py_rows))
    lines.append("")

    env_md_rows: list[list[str]] = []
    for row in env_rows:
        env_md_rows.append(
            [
                str(row.get("date", "-")),
                str(row.get("scope", "-")),
                str(row.get("hardware", "-")),
                str(row.get("python", "-")),
                str(row.get("torch", "-")),
                str(row.get("status", "-")),
                str(row.get("notes", "-")).replace("\n", " "),
            ]
        )
    if not env_md_rows:
        env_md_rows = [["-", "-", "-", "-", "-", "-", "-"]]

    lines.append("#### Tested Environment Snapshot")
    lines.append("")
    lines.append(
        _md_table(
            ["Date", "Scope", "Hardware", "Python", "Torch", "Status", "Notes"],
            env_md_rows,
        )
    )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[1])
    p.add_argument("--pyproject", type=Path, default=Path("pyproject.toml"))
    p.add_argument("--tested-env-json", type=Path, default=Path("docs/tested_environments.json"))
    p.add_argument("--contract-json", type=Path, default=Path("docs/test_matrix_contract.json"))
    p.add_argument("--readme", type=Path, default=Path("README.md"))
    p.add_argument("--docs-page", type=Path, default=Path("docs/test_matrix.md"))
    p.add_argument("--check", action="store_true")
    args = p.parse_args()

    root = args.repo_root.resolve()
    pyproject_path = (root / args.pyproject).resolve()
    tested_path = (root / args.tested_env_json).resolve()
    contract_path = (root / args.contract_json).resolve()
    readme_path = (root / args.readme).resolve()
    docs_path = (root / args.docs_page).resolve()

    py_versions = _load_pyproject_python_versions(pyproject_path)
    env_rows = json.loads(tested_path.read_text(encoding="utf-8"))
    contract = json.loads(contract_path.read_text(encoding="utf-8"))

    payload = _render_payload(py_versions=py_versions, env_rows=env_rows, contract=contract)
    readme_next = _replace_between(readme_path.read_text(encoding="utf-8"), README_START, README_END, payload)
    docs_next = _replace_between(docs_path.read_text(encoding="utf-8"), DOCS_START, DOCS_END, payload)

    readme_changed = _write_or_check(readme_path, readme_next, check=args.check)
    docs_changed = _write_or_check(docs_path, docs_next, check=args.check)

    print(
        json.dumps(
            {
                "readme_changed": readme_changed,
                "docs_changed": docs_changed,
                "py_versions": py_versions,
                "tested_rows": len(env_rows) if isinstance(env_rows, list) else 0,
                "contract": str(contract_path),
            },
            ensure_ascii=False,
        )
    )

    if args.check and (readme_changed or docs_changed):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
