#!/usr/bin/env python3
"""Generate import/export compatibility matrix docs from JSON source of truth."""

from __future__ import annotations

import argparse
import datetime as dt
import importlib
import json
from pathlib import Path
from typing import Any

README_START = "<!-- AUTO-IMPORT-EXPORT-MATRIX:BEGIN -->"
README_END = "<!-- AUTO-IMPORT-EXPORT-MATRIX:END -->"
DOCS_START = README_START
DOCS_END = README_END


def _load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _save_json(path: Path, payload: Any) -> None:
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def _norm(value: Any) -> str:
    if value is None:
        return "-"
    if isinstance(value, list):
        if not value:
            return "-"
        return "<br>".join(str(x) for x in value)
    s = str(value)
    return s if s else "-"


def _md_table(headers: list[str], rows: list[list[str]]) -> str:
    head = "| " + " | ".join(headers) + " |"
    sep = "| " + " | ".join(["---"] * len(headers)) + " |"
    body = ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join([head, sep, *body])


def _replace_between(text: str, start: str, end: str, payload: str) -> str:
    if start not in text or end not in text:
        raise ValueError(f"markers not found: {start} .. {end}")
    left, rest = text.split(start, 1)
    _, right = rest.split(end, 1)
    return left + start + "\n\n" + payload.rstrip() + "\n\n" + end + right


def _write_or_check(path: Path, content: str, check: bool) -> bool:
    old = path.read_text(encoding="utf-8")
    changed = old != content
    if not check and changed:
        path.write_text(content, encoding="utf-8")
    return changed


def _capture_runtime_matrix() -> dict[str, Any]:
    lc_api = importlib.import_module("lightning_core_integrated_api")
    if not hasattr(lc_api, "import_export_compatibility_matrix"):
        raise RuntimeError("lightning_core_integrated_api.import_export_compatibility_matrix is unavailable")
    payload = lc_api.import_export_compatibility_matrix()
    if not isinstance(payload, dict):
        raise TypeError("import_export_compatibility_matrix must return dict")
    payload = dict(payload)
    payload["generated_at_utc"] = dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")
    payload["source"] = "runtime_api"
    return payload


def _render_payload(matrix: dict[str, Any]) -> str:
    rows = list(matrix.get("rows", []))
    table_rows: list[list[str]] = []
    for row in rows:
        row = dict(row)
        table_rows.append(
            [
                _norm(row.get("bridge")),
                _norm("Yes" if bool(row.get("runtime_available", False)) else "No"),
                _norm(row.get("import_kind")),
                _norm(row.get("export_kind")),
                _norm(row.get("dtypes")),
                _norm(row.get("layout")),
                _norm(row.get("shape_constraints")),
                _norm(row.get("zero_copy")),
                _norm(row.get("fallback_reason_codes")),
            ]
        )
    if not table_rows:
        table_rows = [["-"] * 9]

    lines: list[str] = []
    lines.append("### Import/Export Compatibility Matrix (Auto-generated)")
    lines.append("")
    lines.append(f"- Schema version: `{matrix.get('schema_version', '-')}`")
    lines.append(f"- Snapshot generated at (UTC): `{matrix.get('generated_at_utc', '-')}`")
    lines.append("- Source of truth: `docs/import_export_compatibility_matrix.json`")
    lines.append("- Generated by: `python scripts/generate_import_export_matrix_docs.py --refresh-runtime-snapshot`")
    lines.append("")
    lines.append(
        _md_table(
            [
                "Bridge",
                "Runtime Available",
                "Import",
                "Export",
                "DTypes",
                "Layout",
                "Shape Constraints",
                "Zero-Copy",
                "Fallback Reason Codes",
            ],
            table_rows,
        )
    )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[1])
    p.add_argument("--readme", type=Path, default=Path("README.md"))
    p.add_argument("--docs-page", type=Path, default=Path("docs/import_export_matrix.md"))
    p.add_argument("--matrix-json", type=Path, default=Path("docs/import_export_compatibility_matrix.json"))
    p.add_argument("--refresh-runtime-snapshot", action="store_true")
    p.add_argument("--check", action="store_true")
    args = p.parse_args()

    root = args.repo_root.resolve()
    readme_path = (root / args.readme).resolve()
    docs_path = (root / args.docs_page).resolve()
    matrix_json_path = (root / args.matrix_json).resolve()

    if args.refresh_runtime_snapshot:
        matrix = _capture_runtime_matrix()
        _save_json(matrix_json_path, matrix)
    else:
        matrix = _load_json(matrix_json_path)

    payload = _render_payload(matrix)
    readme_next = _replace_between(readme_path.read_text(encoding="utf-8"), README_START, README_END, payload)
    docs_next = _replace_between(docs_path.read_text(encoding="utf-8"), DOCS_START, DOCS_END, payload)

    readme_changed = _write_or_check(readme_path, readme_next, args.check)
    docs_changed = _write_or_check(docs_path, docs_next, args.check)

    print(
        json.dumps(
            {
                "readme_changed": readme_changed,
                "docs_changed": docs_changed,
                "matrix_json": str(matrix_json_path),
                "docs_page": str(docs_path),
            },
            ensure_ascii=False,
        )
    )
    if args.check and (readme_changed or docs_changed):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
